#!/usr/bin/with-contenv bash
set -e

#
# Generated using patorjk.com/software/taag/
#
echo " ######  ########    ###    ########  ######## #### ##    ##  ######   ";
echo "##    ##    ##      ## ##   ##     ##    ##     ##  ###   ## ##    ##  ";
echo "##          ##     ##   ##  ##     ##    ##     ##  ####  ## ##        ";
echo " ######     ##    ##     ## ########     ##     ##  ## ## ## ##   #### ";
echo "      ##    ##    ######### ##   ##      ##     ##  ##  #### ##    ##  ";
echo "##    ##    ##    ##     ## ##    ##     ##     ##  ##   ### ##    ##  ";
echo " ######     ##    ##     ## ##     ##    ##    #### ##    ##  ######   ";

USERNAME=${USERNAME:-app}
PUID=${PUID:-1000}
PGID=${PGID:-1000}

#Create user with specified id
useradd -u ${PUID} -U -d /home/${USERNAME} -s /bin/false ${USERNAME}

# Change gid if necessary
[ "$(id -g ${USERNAME})" -eq "${PGID}" ] || groupmod -o -g ${PGID} ${USERNAME}

echo "
-------------------------------------
    GID/UID
-------------------------------------
Username:    ${USERNAME}
User uid:    $(id -u ${USERNAME})
User gid:    $(id -g ${USERNAME})
"

#mkdir -p /data && chown -R ${USERNAME}:${USERNAME} /data
